# Date:7 oct 2019
## Numpy:(numerical python)
* there are 3 arrays 1d array,2d array,3d array


In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
type(a)

numpy.ndarray

In [8]:
arr_2d=np.array([[1,2,3],[2,3,4]])
arr_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
type(arr_2d)

numpy.ndarray

In [12]:
n=np.array([[1,2,3],[2,3,4],[5,6,7]])
n

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [16]:
l1=[1,2,3,4]
#l1**2
#1,4,3,16
l2=[]
for i in l1:
    l2.append(i**2)
l2

[1, 4, 9, 16]

In [19]:
res=lambda x:x**2
list(map(res,l1))

[1, 4, 9, 16]

In [24]:
[i**2 for i in l1]

[1, 4, 9, 16]

In [20]:
s=np.array([1,2,3,4])
s**2

array([ 1,  4,  9, 16], dtype=int32)

In [35]:
%time
s=np.array([1,2,3,4])
s1=np.array([3,4,5,6])
s+s1

Wall time: 0 ns


array([ 4,  6,  8, 10])

In [34]:
%time
s/s1

Wall time: 0 ns


array([0.33333333, 0.5       , 0.6       , 0.66666667])

In [27]:
s1-s

array([2, 2, 2, 2])

In [28]:
s%s1

array([1, 2, 3, 4], dtype=int32)

In [29]:
s[0]

1

In [30]:
s[1]

2

In [33]:
arr_2d

array([[1, 2, 3],
       [2, 3, 4]])

In [32]:
arr_2d[0][2]

3

In [36]:
range(10)

range(0, 10)

In [38]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [42]:
a2 = np.array(range(1,10,2))
a2

array([1, 3, 5, 7, 9])

In [45]:
a3 = np.linspace(1,10,2)
a3

array([ 1., 10.])

In [46]:
range(1.5,10.5)

TypeError: 'float' object cannot be interpreted as an integer

In [47]:
al = np.arange(1.5,10.2)
al

array([1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [48]:
a2 = np.linspace(1.2,90.4,10)
a2

array([ 1.2       , 11.11111111, 21.02222222, 30.93333333, 40.84444444,
       50.75555556, 60.66666667, 70.57777778, 80.48888889, 90.4       ])

In [49]:
type(a2[0])

numpy.float64

In [51]:
n

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [61]:
arr_3d=np.array([[1,2],[3,4],[5,6]])
arr_3d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
arr_3d.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr_3d.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr_3d.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [65]:
arr_3d.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
n

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [70]:
n.reshape(-1)

array([1, 2, 3, 2, 3, 4, 5, 6, 7])

In [71]:
array=np.array([[2,3],[4,5],[7,8]])

In [72]:
a.itemsize

4

In [73]:
a.ndim

1

In [74]:
array.shape

(3, 2)

In [76]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '

In [79]:
help(np.shape)

Help on function shape in module numpy:

shape(a)
    Return the shape of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    shape : tuple of ints
        The elements of the shape tuple give the lengths of the
        corresponding array dimensions.
    
    See Also
    --------
    alen
    ndarray.shape : Equivalent array method.
    
    Examples
    --------
    >>> np.shape(np.eye(3))
    (3, 3)
    >>> np.shape([[1, 2]])
    (1, 2)
    >>> np.shape([0])
    (1,)
    >>> np.shape(0)
    ()
    
    >>> a = np.array([(1, 2), (3, 4)], dtype=[('x', 'i4'), ('y', 'i4')])
    >>> np.shape(a)
    (2,)
    >>> a.shape
    (2,)



In [80]:
d=np.arange(1,500,9)
d

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100, 109,
       118, 127, 136, 145, 154, 163, 172, 181, 190, 199, 208, 217, 226,
       235, 244, 253, 262, 271, 280, 289, 298, 307, 316, 325, 334, 343,
       352, 361, 370, 379, 388, 397, 406, 415, 424, 433, 442, 451, 460,
       469, 478, 487, 496])

In [81]:
d[6]

55

In [82]:
d[55]#0-55

496

In [83]:
np.ones((1,2))

array([[1., 1.]])

In [86]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [87]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [88]:
np.eye(100,50)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [90]:
np.eye((10),dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [91]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [92]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [93]:
np.eye(3,k=0)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
np.eye(10,k=5)

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [95]:
array

array([[2, 3],
       [4, 5],
       [7, 8]])

In [96]:
np.transpose(array)

array([[2, 4, 7],
       [3, 5, 8]])

In [98]:
f=np.random.randint(100,500,(25,6))
f

array([[301, 433, 495, 169, 214, 208],
       [395, 463, 393, 185, 259, 180],
       [243, 317, 368, 359, 401, 103],
       [457, 426, 154, 336, 197, 130],
       [444, 103, 356, 393, 110, 188],
       [101, 211, 159, 195, 288, 386],
       [415, 146, 187, 474, 199, 201],
       [275, 474, 150, 379, 479, 191],
       [115, 144, 203, 384, 205, 438],
       [364, 359, 290, 153, 362, 442],
       [409, 133, 346, 100, 307, 492],
       [409, 396, 235, 106, 299, 403],
       [414, 393, 125, 382, 483, 421],
       [145, 205, 204, 388, 374, 204],
       [324, 420, 316, 189, 399, 458],
       [231, 183, 494, 179, 415, 335],
       [168, 245, 134, 295, 262, 134],
       [450, 468, 284, 487, 115, 382],
       [495, 456, 326, 204, 415, 368],
       [308, 439, 382, 246, 212, 486],
       [178, 429, 337, 199, 167, 174],
       [108, 168, 354, 472, 192, 166],
       [113, 179, 192, 391, 467, 421],
       [110, 361, 233, 235, 153, 368],
       [328, 147, 283, 372, 467, 253]])

In [100]:
f.shape

(25, 6)

In [101]:
f[1:]

array([[395, 463, 393, 185, 259, 180],
       [243, 317, 368, 359, 401, 103],
       [457, 426, 154, 336, 197, 130],
       [444, 103, 356, 393, 110, 188],
       [101, 211, 159, 195, 288, 386],
       [415, 146, 187, 474, 199, 201],
       [275, 474, 150, 379, 479, 191],
       [115, 144, 203, 384, 205, 438],
       [364, 359, 290, 153, 362, 442],
       [409, 133, 346, 100, 307, 492],
       [409, 396, 235, 106, 299, 403],
       [414, 393, 125, 382, 483, 421],
       [145, 205, 204, 388, 374, 204],
       [324, 420, 316, 189, 399, 458],
       [231, 183, 494, 179, 415, 335],
       [168, 245, 134, 295, 262, 134],
       [450, 468, 284, 487, 115, 382],
       [495, 456, 326, 204, 415, 368],
       [308, 439, 382, 246, 212, 486],
       [178, 429, 337, 199, 167, 174],
       [108, 168, 354, 472, 192, 166],
       [113, 179, 192, 391, 467, 421],
       [110, 361, 233, 235, 153, 368],
       [328, 147, 283, 372, 467, 253]])

In [102]:
f[6]#6 th row

array([415, 146, 187, 474, 199, 201])

In [103]:
f[[3,4,5]]

array([[457, 426, 154, 336, 197, 130],
       [444, 103, 356, 393, 110, 188],
       [101, 211, 159, 195, 288, 386]])

In [104]:
f[:2]

array([[301, 433, 495, 169, 214, 208],
       [395, 463, 393, 185, 259, 180]])

In [105]:
f[2,[3,4]]

array([359, 401])

In [106]:
f[[2,3,4],[2,3,4]]

array([368, 336, 110])

In [112]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [113]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [114]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [115]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [116]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [118]:
np.full((1,3),7)# 7 is the filling  num 

array([[7, 7, 7]])

In [120]:
s=np.array([[[1,2],[3,4]],[[5,6],[8,9]]])
s

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [8, 9]]])

In [121]:
s.flatten()

array([1, 2, 3, 4, 5, 6, 8, 9])

In [125]:
help(np.tile)

Help on function tile in module numpy:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of repetitions of `A`

In [122]:
np.tile(s,2)

array([[[1, 2, 1, 2],
        [3, 4, 3, 4]],

       [[5, 6, 5, 6],
        [8, 9, 8, 9]]])

In [124]:
np.tile(s,[2,2])

array([[[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]],

       [[5, 6, 5, 6],
        [8, 9, 8, 9],
        [5, 6, 5, 6],
        [8, 9, 8, 9]]])

In [127]:
s.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 9]])

In [128]:
import math

In [129]:
math.pi#package.attribute

3.141592653589793

In [130]:
math.pow(2,3)

8.0

In [131]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [132]:
help(math.tan)

Help on built-in function tan in module math:

tan(x, /)
    Return the tangent of x (measured in radians).



# docs.scipy.org/doc